require "yajl"
require "open-uri"
require "thor"

require "xbox-api/version"
require "xbox-api/client"
require "xbox-api/game_data"
require "xbox-api/game"
require "xbox-api/gamer"
require "xbox-api/user"
require_relative "xbox-api/xboxlive"
# require "xbox-api/xboxlive"
